/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__cython_knn
#define __PYX_HAVE__cython_knn


#ifndef __PYX_HAVE_API__cython_knn

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) __pyx_v_x;

#endif /* !__PYX_HAVE_API__cython_knn */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcython_knn(void);
#else
PyMODINIT_FUNC PyInit_cython_knn(void);
#endif

#endif /* !__PYX_HAVE__cython_knn */
